### PR TITLE
Add support for ephemeral topics

### PR DESCRIPTION
**Pull request by Nomon**
NSQ now has support for ephemeral topics in addition to ephemeral channels.
This change changes the regex to match that change.
https://github.com/bitly/nsq/pull/305

### CODE REVIEW

**Comment by juliangruber** [comment]
lgtm, a test would help though

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
Would be nice with a feature where you could set e.g. `ephemeral: true` when creating the `nsq` object and it could append `#ephemeral` to all topics

**Comment by juliangruber** [comment]
@ralphtheninja what's the use case?

**Comment by ralphtheninja** [comment]
This might be the wrong place for this discussion. The idea I had was to be able to use normal topics in your code and be able to flip an ephemeral switch to automatically make ephemeral topics.

**Pull request merged**
