### PR TITLE
add test script in package.json

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by juliangruber** [comment]
or better `"make test"`

**Comment by juliangruber** [comment]
so there's only one place to update

**Comment by ralphtheninja** [comment]
On it.

**Comment by juliangruber** [comment]
+1

**Comment by ralphtheninja** [comment]
At first I didn't notice the `Makefile` :)

**Comment by ralphtheninja** [comment]
*bump*

**Pull request merged**
