### PR TITLE
Max attempts

### PR DESCRIPTION
**Pull request by ralphtheninja**
If `maxAttempts` is set to 1 a message will *always* be discarded. This feels wrong. I refactored some of the test code so I could reuse frame data.

### CODE REVIEW

**Comment by dweinstein** [comment]
:+1:  Magnus and I both ran into this

**Comment by juliangruber** [comment]
+1

**Comment by ralphtheninja** [comment]
*bump* :)

**Comment by ralphtheninja** [comment]
Awesome. Thanks!

**Pull request merged**
