### PR TITLE
Update nsq-lookup

### PR DESCRIPTION
**Pull request by jcrugzz**
Trying to get this to work on the latest node. Currently this is using my fork of `nsq-lookup` until https://github.com/segmentio/nsq-lookup/pull/5 is merged. Wanted tests to run on CI

### CODE REVIEW

**Comment by jcrugzz** [comment]
@thehydroimpulse could circle.ci be configured to run on PRs as well? and any assistance with both this and `nsq-lookup` would be great :).

**Comment by thehydroimpulse** [comment]
Thanks for the PR. I enabled ci on PRs but you may need to close and reopen

**Comment by jcrugzz** [comment]
@thehydroimpulse will update with latest `nsq-lookup` whenever version is bumped :).

**Comment by jcrugzz** [comment]
@thehydroimpulse only fails due to timing and publish status of nsq-lookup. If y'all want help and are willing to give privileges, I'm happy to assist. Thanks again for the quick response!

**Comment by jcrugzz** [comment]
@thehydroimpulse any chance we could have https://github.com/segmentio/nsq-lookup published so we can get this merged and published as well? Thanks!

**Comment by thehydroimpulse** [comment]
hey @jcrugzz sorry for the delay here. I just published nsq-lookup to npm

**Comment by jcrugzz** [comment]
@thehydroimpulse great thanks :). This one should be good to go then

**Comment by thehydroimpulse** [comment]
Thanks again for the PR!

**Pull request merged**
