### PR TITLE
Set reader's 'timer' attribute

### PR DESCRIPTION
**Pull request by poying**

### CODE REVIEW

**Comment by juliangruber** [comment]
can you explain why you need this change?

**Comment by poying** [comment]
@juliangruber 
Reader uses `clearInterval(this.timer)` to stop polling nsqlookd in `.close()` method, but it never sets interval ID to `.timer`.

https://github.com/segmentio/nsq.js/blob/master/lib/reader.js#L328

**Comment by juliangruber** [comment]
Aah lgtm! Tbh I never used that method. We should also add a test for this

**Comment by poying** [comment]
@juliangruber

We don't need `.closing` if we have already used clearInterval in `.close()` method, so I remove all of them.

**Comment by juliangruber** [comment]
The implementation changes lgtm, but I'm not convinced about the tests, since they're mostly testing internal properties.

@tj any suggestions?

**Comment by tj** [comment]
woah yikes, _dynamically typed_. I agree that the tests might get screwed later but for now it LGTM

**Comment by juliangruber** [comment]
ok cool, can we get this merged then?

**Pull request merged**
